spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NATIONAL_RESTAURANT_STANDARD
    username: root
    password: smlee3264
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

# p6spy (use not in production environment)
logging:
  level:
    p6spy: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
